import React from "react";
import { motion } from "framer-motion";
import { Link, Navigate, Route, Routes, useNavigate } from "react-router-dom";
import { ApiError, authApi, CaseDetail, Dashboard, employerApi, evidenceApi, Language, ngoApi, NgoCase, workerApi } from "./api";

const labels = {
  hi: {
    home: "मुख्य पृष्ठ", how: "यह कैसे काम करता है", workers: "श्रमिकों के लिए", orgs: "संस्थाओं के लिए", safety: "सुरक्षा", about: "हमारे बारे में", join: "पायलट से जुड़ें",
    login: "श्रमिक लॉगिन", phone: "मोबाइल नंबर", sendOtp: "OTP भेजें", otp: "OTP डालें", verify: "सत्यापित करें", demo: "डेमो OTP: 123456", dashboard: "मेरा डैशबोर्ड", wages: "मजदूरी", checkin: "सुरक्षा जांच", complaint: "समस्या बताएं", cases: "मेरे मामले", logout: "लॉग आउट", confirmLogout: "क्या आप लॉग आउट करना चाहते हैं?", emergencyDisclaimer: "Pehchaan does not replace emergency services, police, courts, or labour departments. It helps workers and trusted organizations organize information and access support more effectively.", emergencyNumber: "तत्काल खतरे में 112 पर कॉल करें।",
    promised: "वादा की गई रकम", received: "मिली रकम", date: "तारीख", note: "काम/नियोक्ता का नोट", save: "सहेजें", safe: "मैं सुरक्षित हूं", help: "मुझे मदद चाहिए", summary: "समस्या का विवरण", type: "समस्या का प्रकार", submit: "भेजें", loading: "लोड हो रहा है...", retry: "फिर कोशिश करें", offline: "आप ऑफलाइन दिख रहे हैं। कनेक्शन आने पर यह काम अपने आप दोबारा कोशिश होगा।", error: "जानकारी लोड नहीं हो सकी। कृपया कनेक्शन जांचकर फिर कोशिश करें।", pending: "भेजने की कतार में", noData: "अभी कोई जानकारी नहीं है।",
  },
  en: {
    home: "Home", how: "How It Works", workers: "For Workers", orgs: "For Organizations", safety: "Safety", about: "About", join: "Join the Pilot",
    login: "Worker login", phone: "Mobile number", sendOtp: "Send OTP", otp: "Enter OTP", verify: "Verify", demo: "Demo OTP: 123456", dashboard: "My dashboard", wages: "Wages", checkin: "Safety check-in", complaint: "Report a problem", cases: "My cases", logout: "Log out", confirmLogout: "Do you want to log out?", emergencyDisclaimer: "Pehchaan does not replace emergency services, police, courts, or labour departments. It helps workers and trusted organizations organize information and access support more effectively.", emergencyNumber: "If you are in immediate danger, call 112.",
    promised: "Promised amount", received: "Received amount", date: "Date", note: "Employer/site note", save: "Save", safe: "I'm safe", help: "I need help", summary: "Problem summary", type: "Problem type", submit: "Submit", loading: "Loading...", retry: "Try again", offline: "You appear to be offline. This will retry automatically when your connection returns.", error: "Could not load your information. Please check your connection and try again.", pending: "Queued to send", noData: "Nothing here yet.",
  },
} as const;

const publicPhotos = { hero: "https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1800&q=80", worker: "https://images.unsplash.com/photo-1521791055366-0d553872125f?auto=format&fit=crop&w=900&q=80" };
const sessionKey = "pehchaan-worker-session";
type Session = { token: string; refreshToken: string; workerId: string; expiresAt: number };
type QueueItem = { id: string; kind: "checkin" | "case"; body: Record<string, unknown> };

function getSession(): Session | null {
  try {
    const session = JSON.parse(localStorage.getItem(sessionKey) || "null") as Session | null;
    return session && session.expiresAt > Date.now() ? session : null;
  } catch { return null; }
}

function isOffline(error: unknown) { return Boolean((error as ApiError)?.offline); }
function translatedCaseType(lang: Language, type: string) {
  const values = lang === "hi"
    ? { wage_theft: "मजदूरी नहीं मिली", unsafe_site: "असुरक्षित जगह", harassment: "उत्पीड़न" }
    : { wage_theft: "Unpaid wages", unsafe_site: "Unsafe site", harassment: "Harassment" };
  return values[type as keyof typeof values] || type;
}
function translatedStatus(lang: Language, status: string) {
  const values = lang === "hi"
    ? { new: "नया", assigned: "सौंपा गया", in_progress: "काम चल रहा है", resolved: "हल हो गया" }
    : { new: "New", assigned: "Assigned", in_progress: "In progress", resolved: "Resolved" };
  return values[status as keyof typeof values] || status;
}
function queueWork(item: QueueItem) {
  const queue = JSON.parse(localStorage.getItem("pehchaan-offline-queue") || "[]") as QueueItem[];
  localStorage.setItem("pehchaan-offline-queue", JSON.stringify([...queue, item]));
}

function Navbar({ lang, setLang }: { lang: Language; setLang: (value: Language) => void }) {
  const t = labels[lang];
  return <header className="navbar"><Link className="brand" to="/">{lang === "hi" ? "पहचान" : "Pehchaan"}<span>.</span></Link><nav><Link to="/">{t.home}</Link><Link to="/how-it-works">{t.how}</Link><Link to="/for-workers">{t.workers}</Link><Link to="/for-organizations">{t.orgs}</Link><Link to="/safety">{t.safety}</Link><Link to="/about">{t.about}</Link></nav><div className="nav-actions"><button className="language" onClick={() => setLang(lang === "hi" ? "en" : "hi")}>{lang === "hi" ? "EN" : "हिंदी"} ↔</button><Link className="button button-small" to="/join">{t.join}</Link></div></header>;
}

function PublicHome({ lang }: { lang: Language }) {
  const t = labels[lang];
  const hi = lang === "hi";
  return <main><section className="hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(8,32,46,.9), rgba(8,32,46,.3)), url(${publicPhotos.hero})` }}><div className="hero-content"><p className="eyebrow">{hi ? "सुरक्षित भविष्य की शुरुआत अपनी बात कहने से होती है" : "A safer future starts with being heard"}</p><h1>{hi ? "हर श्रमिक सुरक्षित कल का हकदार है" : "Every Worker Deserves a Safer Tomorrow"}</h1><p className="hero-copy">{hi ? "पहचान प्रवासी श्रमिकों को मजदूरी सुरक्षित रखने, असुरक्षित परिस्थितियों की सूचना देने और भरोसेमंद सहायता से जुड़ने में मदद करता है।" : "Pehchaan helps migrant workers protect wages, report unsafe conditions, and connect with trusted support."}</p><div className="hero-actions"><Link className="button" to="/worker/login">{t.login} →</Link><Link className="button button-ghost" to="/how-it-works">{t.how}</Link></div></div></section></main>;
}

function Auth({ lang, setSession }: { lang: Language; setSession: (session: Session) => void }) {
  const t = labels[lang]; const [phone, setPhone] = React.useState(""); const [otp, setOtp] = React.useState(""); const [sent, setSent] = React.useState(false); const [busy, setBusy] = React.useState(false); const [error, setError] = React.useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { if (!sent) { await authApi.requestOtp(phone); setSent(true); } else { const result = await authApi.verifyOtp(phone, otp); setSession({ token: result.accessToken, refreshToken: result.refreshToken, workerId: result.user.id, expiresAt: Date.now() + 15 * 60 * 1000 }); } } catch (cause) { setError(isOffline(cause) ? t.offline : t.error); } finally { setBusy(false); } };
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><p className="eyebrow teal">{t.login}</p><h1>{sent ? t.otp : t.phone}</h1><input required type={sent ? "text" : "tel"} value={sent ? otp : phone} onChange={(event) => sent ? setOtp(event.target.value) : setPhone(event.target.value)} placeholder={sent ? "123456" : "+91 98765 43210"} /><button className="button" disabled={busy}>{busy ? t.loading : sent ? t.verify : t.sendOtp}</button>{sent && <p className="helper">{t.demo}</p>}{error && <p className="error">{error}</p>}</form></main>;
}

function WorkerLayout({ lang, dashboard, logout, children }: { lang: Language; dashboard: Dashboard; logout: () => void; children: React.ReactNode }) {
  const t = labels[lang]; const navigate = useNavigate();
  return <main className="worker-app"><aside className="worker-nav"><Link className="brand" to="/worker">{lang === "hi" ? "पहचान" : "Pehchaan"}<span>.</span></Link><button onClick={() => navigate("/worker")}>{t.dashboard}</button><button onClick={() => navigate("/worker/wages")}>{t.wages}</button><button onClick={() => navigate("/worker/check-in")}>{t.checkin}</button><button onClick={() => navigate("/worker/report")}>{t.complaint}</button><button onClick={() => navigate("/worker/cases")}>{t.cases}</button><button className="logout-link" onClick={logout}>{t.logout}</button></aside><section className="worker-content">{children}</section></main>;
}

function Loading({ lang }: { lang: Language }) { return <div className="loading-card" aria-live="polite">{labels[lang].loading}</div>; }
function ErrorBox({ lang, offline, onRetry }: { lang: Language; offline?: boolean; onRetry: () => void }) { const t = labels[lang]; return <div className="error-box"><p>{offline ? t.offline : t.error}</p><button className="button button-small" onClick={onRetry}>{t.retry}</button></div>; }

function DashboardHome({ lang, dashboard }: { lang: Language; dashboard: Dashboard }) {
  const t = labels[lang]; const pending = dashboard.wageEntries.reduce((sum, item) => sum + item.amount, 0); const latest = dashboard.checkIns.at(-1);
  return <><h1>{t.dashboard}</h1><div className="stats-grid"><div className="stat-card"><span>{t.wages}</span><strong>₹{pending}</strong></div><div className="stat-card"><span>{t.checkin}</span><strong>{latest?.status === "unsafe" || latest?.status === "emergency" ? t.help : t.safe}</strong></div><div className="stat-card"><span>{t.cases}</span><strong>{dashboard.cases.length}</strong></div></div><div className="worker-cards"><Link className="worker-card" to="/worker/wages"><h2>{t.wages}</h2><p>{dashboard.wageEntries.length ? `${dashboard.wageEntries.length} ${lang === "hi" ? "रिकॉर्ड" : "records"}` : t.noData}</p></Link><Link className="worker-card" to="/worker/check-in"><h2>{t.checkin}</h2><p>{latest?.notes || t.noData}</p></Link><Link className="worker-card" to="/worker/report"><h2>{t.complaint}</h2><p>{t.summary}</p></Link></div></>;
}

function Wages({ lang, dashboard, refresh }: { lang: Language; dashboard: Dashboard; refresh: () => Promise<void> }) {
  const t = labels[lang]; const [busy, setBusy] = React.useState(false); const [error, setError] = React.useState(""); const [form, setForm] = React.useState({ promised: "", received: "", date: new Date().toISOString().slice(0, 10), note: "" });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { await workerApi.addWage({ workerId: dashboard.worker.id, amount: Number(form.received || form.promised), type: form.received ? "received" : "promised", date: form.date, notes: form.note }); await refresh(); setForm({ ...form, promised: "", received: "", note: "" }); } catch (cause) { setError(isOffline(cause) ? t.offline : t.error); } finally { setBusy(false); } };
  return <><h1>{t.wages}</h1>{error && <ErrorBox lang={lang} offline={error === t.offline} onRetry={() => setError("")} />}<form className="worker-form" onSubmit={submit}><label>{t.promised}<input type="number" value={form.promised} onChange={(e) => setForm({ ...form, promised: e.target.value })} /></label><label>{t.received}<input type="number" value={form.received} onChange={(e) => setForm({ ...form, received: e.target.value })} /></label><label>{t.date}<input type="date" required value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></label><label>{t.note}<textarea value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} /></label><button className="button" disabled={busy}>{busy ? t.loading : t.save}</button></form><div className="list-panel">{dashboard.wageEntries.map((entry) => <div className="list-row" key={entry.id}><strong>₹{entry.amount}</strong><span>{entry.type} · {entry.date}</span></div>)}</div></>;
}

function CheckIn({ lang, dashboard, refresh }: { lang: Language; dashboard: Dashboard; refresh: () => Promise<void> }) {
  const t = labels[lang]; const [busy, setBusy] = React.useState(false); const [error, setError] = React.useState(""); const [locationConsent, setLocationConsent] = React.useState(false);
  const submit = async (status: "safe" | "unsafe") => { const body = { workerId: dashboard.worker.id, status, locationConsent, location: null, notes: status === "safe" ? "Worker reported safe." : "Worker requested help." }; setBusy(true); setError(""); try { await workerApi.checkIn(body); await refresh(); } catch (cause) { if (isOffline(cause)) { queueWork({ id: crypto.randomUUID(), kind: "checkin", body }); setError(t.offline); } else setError(t.error); } finally { setBusy(false); } };
  return <><h1>{t.checkin}</h1>{error && <ErrorBox lang={lang} offline={error === t.offline} onRetry={() => setError("")} />}<div className="list-panel"><p>{t.emergencyDisclaimer}</p><strong>{t.emergencyNumber}</strong><label><input type="checkbox" checked={locationConsent} onChange={(e) => setLocationConsent(e.target.checked)} /> {lang === "hi" ? "मैं इस check-in के लिए अपना स्थान साझा करने की सहमति देता/देती हूं।" : "I consent to sharing my location for this check-in."}</label></div><div className="checkin-actions"><button className="big-action safe-action" disabled={busy} onClick={() => submit("safe")}>✓<span>{t.safe}</span></button><button className="big-action help-action" disabled={busy} onClick={() => submit("unsafe")}>!<span>{t.help}</span></button></div><div className="list-panel">{dashboard.checkIns.slice().reverse().map((item) => <div className="list-row" key={item.id}><strong>{item.status === "safe" ? t.safe : t.help}</strong><span>{new Date(item.createdAt).toLocaleString()}</span></div>)}</div></>;
}

function Report({ lang, dashboard, refresh }: { lang: Language; dashboard: Dashboard; refresh: () => Promise<void> }) {
  const t = labels[lang]; const [busy, setBusy] = React.useState(false); const [error, setError] = React.useState(""); const [summary, setSummary] = React.useState(""); const [type, setType] = React.useState("wage_theft"); const [danger, setDanger] = React.useState(false); const [now, setNow] = React.useState(false); const [locationConsent, setLocationConsent] = React.useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const body = { workerId: dashboard.worker.id, type, priority: danger || now ? "high" : "medium", summary, immediateDanger: danger, happeningNow: now, locationConsent, location: null }; setBusy(true); setError(""); try { await workerApi.createCase(body); setSummary(""); await refresh(); } catch (cause) { if (isOffline(cause)) { queueWork({ id: crypto.randomUUID(), kind: "case", body }); setError(t.offline); } else setError(t.error); } finally { setBusy(false); } };
  return <><h1>{t.complaint}</h1>{error && <ErrorBox lang={lang} offline={error === t.offline} onRetry={() => setError("")} />}<form className="worker-form" onSubmit={submit}><label>{t.type}<select value={type} onChange={(e) => setType(e.target.value)}><option value="wage_theft">{lang === "hi" ? "मजदूरी नहीं मिली" : "Unpaid wages"}</option><option value="unsafe_site">{lang === "hi" ? "असुरक्षित जगह" : "Unsafe site"}</option><option value="harassment">{lang === "hi" ? "उत्पीड़न" : "Harassment"}</option></select></label><label>{t.summary}<textarea required rows={6} value={summary} onChange={(e) => setSummary(e.target.value)} /></label><label><input type="checkbox" checked={danger} onChange={(e) => setDanger(e.target.checked)} /> {lang === "hi" ? "मैं तत्काल खतरे में हूं" : "I am in immediate danger"}</label><label><input type="checkbox" checked={now} onChange={(e) => setNow(e.target.checked)} /> {lang === "hi" ? "यह अभी हो रहा है" : "This is happening right now"}</label>{(danger || now) && <div className="list-panel"><p>{t.emergencyDisclaimer}</p><strong>{t.emergencyNumber}</strong><label><input type="checkbox" checked={locationConsent} onChange={(e) => setLocationConsent(e.target.checked)} /> {lang === "hi" ? "मैं इस शिकायत के लिए अपना स्थान साझा करने की सहमति देता/देती हूं।" : "I consent to sharing my location for this complaint."}</label></div>}<button className="button" disabled={busy}>{busy ? t.loading : t.submit}</button></form></>;
}

function Cases({ lang, dashboard }: { lang: Language; dashboard: Dashboard }) { const t = labels[lang]; return <><h1>{t.cases}</h1><div className="list-panel">{dashboard.cases.length ? dashboard.cases.map((item) => <div className="list-row" key={item.id}><strong>{translatedCaseType(lang, item.type)}</strong><span>{translatedStatus(lang, item.status)} · {item.priority} · {new Date(item.createdAt).toLocaleDateString()}</span><p>{item.summary}</p></div>) : <p>{t.noData}</p>}</div></>; }

function WorkerArea({ lang, session, logout }: { lang: Language; session: Session; logout: () => void }) {
  const [dashboard, setDashboard] = React.useState<Dashboard | null>(null); const [loading, setLoading] = React.useState(true); const [offline, setOffline] = React.useState(false);
  const refresh = React.useCallback(async () => { setLoading(true); try { setDashboard(await workerApi.dashboard(session.workerId)); setOffline(false); } catch (cause) { setOffline(isOffline(cause)); } finally { setLoading(false); } }, [session.workerId]);
  React.useEffect(() => { void refresh(); }, [refresh]);
  React.useEffect(() => { const sync = async () => { const queue = JSON.parse(localStorage.getItem("pehchaan-offline-queue") || "[]") as QueueItem[]; if (!queue.length) return; const remaining: QueueItem[] = []; for (const item of queue) { try { if (item.kind === "checkin") await workerApi.checkIn(item.body); else await workerApi.createCase(item.body); } catch { remaining.push(item); } } localStorage.setItem("pehchaan-offline-queue", JSON.stringify(remaining)); if (!remaining.length) void refresh(); }; window.addEventListener("online", sync); void sync(); return () => window.removeEventListener("online", sync); }, [refresh]);
  if (loading && !dashboard) return <WorkerLayout lang={lang} dashboard={{ worker: { id: session.workerId, phone: "", role: "worker", language: lang, profile: {} }, wageEntries: [], checkIns: [], cases: [] }} logout={logout}><Loading lang={lang} /></WorkerLayout>;
  if (!dashboard) return <WorkerLayout lang={lang} dashboard={{ worker: { id: session.workerId, phone: "", role: "worker", language: lang, profile: {} }, wageEntries: [], checkIns: [], cases: [] }} logout={logout}><ErrorBox lang={lang} offline={offline} onRetry={() => void refresh()} /></WorkerLayout>;
  return <WorkerLayout lang={lang} dashboard={dashboard} logout={logout}>{offline && <ErrorBox lang={lang} offline onRetry={() => void refresh()} />}<Routes><Route index element={<DashboardHome lang={lang} dashboard={dashboard} />} /><Route path="wages" element={<Wages lang={lang} dashboard={dashboard} refresh={refresh} />} /><Route path="check-in" element={<CheckIn lang={lang} dashboard={dashboard} refresh={refresh} />} /><Route path="report" element={<Report lang={lang} dashboard={dashboard} refresh={refresh} />} /><Route path="cases" element={<Cases lang={lang} dashboard={dashboard} />} /></Routes></WorkerLayout>;
}

function PublicPage({ lang, title }: { lang: Language; title: string }) { return <main className="page-hero"><p className="eyebrow">{title}</p><h1>{lang === "hi" ? "सुरक्षित सहायता तक एक साफ रास्ता।" : "A clear path to safer support."}</h1><p>{lang === "hi" ? "यह जानकारी पेज जल्द ही और विस्तार से उपलब्ध होगा।" : "This information page will be expanded soon."}</p></main>; }

const ngoText = {
  hi: { login: "संस्था लॉगिन", email: "ईमेल", password: "पासवर्ड", signIn: "लॉगिन करें", demo: "डेमो: ngo@pehchaan.org / demo", inbox: "केस इनबॉक्स", audit: "ऑडिट लॉग", all: "सभी", fresh: "नए", high: "उच्च प्राथमिकता", mine: "मुझे सौंपे गए", search: "केस या श्रमिक खोजें", noCases: "अभी कोई मामला नहीं है।", retry: "फिर कोशिश करें", loading: "लोड हो रहा है...", error: "जानकारी लोड नहीं हो सकी। कनेक्शन जांचकर फिर कोशिश करें।", assigned: "सौंपें", status: "स्थिति", note: "नोट जोड़ें", add: "जोड़ें", evidence: "प्रमाण", upload: "प्रमाण अपलोड करें", download: "डाउनलोड करें", scanning: "सुरक्षा जांच लंबित", notes: "नोट्स", history: "इतिहास", acknowledge: "अलर्ट स्वीकार करें", acknowledged: "स्वीकार किया गया", back: "इनबॉक्स पर लौटें", save: "सहेजें", logout: "लॉग आउट", logoutConfirm: "क्या आप लॉग आउट करना चाहते हैं?" },
  en: { login: "Organization login", email: "Email", password: "Password", signIn: "Sign in", demo: "Demo: ngo@pehchaan.org / demo", inbox: "Case inbox", audit: "Audit log", all: "All", fresh: "New", high: "High priority", mine: "Assigned to me", search: "Search case or worker", noCases: "No cases yet.", retry: "Try again", loading: "Loading...", error: "Could not load this information. Check your connection and try again.", assigned: "Assign", status: "Status", note: "Add note", add: "Add", evidence: "Evidence", upload: "Upload evidence", download: "Download", scanning: "Security scan pending", notes: "Notes", history: "History", acknowledge: "Acknowledge alert", acknowledged: "Acknowledged", back: "Back to inbox", save: "Save", logout: "Log out", logoutConfirm: "Do you want to log out?" },
} as const;

type NgoSession = { email: string; token: string; refreshToken: string; expiresAt: number };
const ngoSessionKey = "pehchaan-ngo-session";
function getNgoSession(): NgoSession | null { try { const value = JSON.parse(localStorage.getItem(ngoSessionKey) || "null") as NgoSession | null; return value && value.expiresAt > Date.now() ? value : null; } catch { return null; } }

function NgoLogin({ lang, setSession }: { lang: Language; setSession: (session: NgoSession) => void }) {
  const t = ngoText[lang]; const [email, setEmail] = React.useState(""); const [password, setPassword] = React.useState(""); const [error, setError] = React.useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); try { const result = await authApi.ngoLogin(email, password); const session = { email, token: result.accessToken, refreshToken: result.refreshToken, expiresAt: Date.now() + result.expiresIn * 1000 }; localStorage.setItem(ngoSessionKey, JSON.stringify(session)); setSession(session); } catch { setError(lang === "hi" ? "संगठन की जानकारी गलत है या सर्वर उपलब्ध नहीं है।" : "Organization credentials are invalid or the server is unavailable."); } };
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><p className="eyebrow teal">{t.login}</p><h1>{t.login}</h1><label>{t.email}<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>{t.password}<input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label><button className="button">{t.signIn}</button><p className="helper">{t.demo}</p>{error && <p className="error">{error}</p>}</form></main>;
}

function NgoNav({ lang, logout }: { lang: Language; logout: () => void }) {
  const t = ngoText[lang]; const navigate = useNavigate();
  return <aside className="worker-nav ngo-nav"><Link className="brand" to="/ngo">{lang === "hi" ? "पहचान" : "Pehchaan"}<span>.</span></Link><button onClick={() => navigate("/ngo")}>{t.inbox}</button><button onClick={() => navigate("/ngo/audit")}>{t.audit}</button><button className="logout-link" onClick={logout}>{t.logout}</button></aside>;
}

function NgoInbox({ lang }: { lang: Language }) {
  const t = ngoText[lang]; const [cases, setCases] = React.useState<NgoCase[]>([]); const [alerts, setAlerts] = React.useState<import("./api").Alert[]>([]); const [filter, setFilter] = React.useState("all"); const [search, setSearch] = React.useState(""); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState(false);
  const load = React.useCallback(async () => { setLoading(true); try { const [result, alertResult] = await Promise.all([ngoApi.cases(), ngoApi.alerts()]); setCases(result.cases); setAlerts(alertResult.alerts); setError(false); } catch { setError(true); } finally { setLoading(false); } }, []);
  React.useEffect(() => { void load(); }, [load]);
  const visible = cases.filter((item) => filter === "all" || (filter === "new" && item.status === "new") || (filter === "high" && item.priority === "high") || (filter === "mine" && Boolean(item.owner))).filter((item) => `${item.id} ${item.workerId} ${item.summary}`.toLowerCase().includes(search.toLowerCase()));
  if (loading) return <Loading lang={lang} />;
  if (error) return <div className="error-box"><p>{t.error}</p><button className="button button-small" onClick={() => void load()}>{t.retry}</button></div>;
  return <><div className="ngo-heading"><div><p className="eyebrow teal">Pehchaan NGO</p><h1>{t.inbox}</h1></div><input className="ngo-search" placeholder={t.search} value={search} onChange={(e) => setSearch(e.target.value)} /></div>{alerts.filter((alert) => alert.status === "pending" || alert.status === "escalated").map((alert) => <div className="alert-card" key={alert.id}><strong>{lang === "hi" ? "तत्काल सुरक्षा अलर्ट" : "Urgent safety alert"}</strong><span>{new Date(alert.createdAt).toLocaleString()}</span><button className="button button-small" onClick={() => void ngoApi.updateAlert(alert.id, { action: "acknowledge", actionTaken: "Caseworker contacted and reviewing." }).then(() => void load())}>{lang === "hi" ? "स्वीकार करें" : "Acknowledge"}</button></div>)}<div className="filter-row">{[["all", t.all], ["new", t.fresh], ["high", t.high], ["mine", t.mine]].map(([value, label]) => <button className={filter === value ? "filter active" : "filter"} onClick={() => setFilter(value)} key={value}>{label}</button>)}</div><div className="list-panel">{visible.length ? visible.map((item) => <Link className="list-row case-row" to={`/ngo/cases/${item.id}`} key={item.id}><div><strong>{translatedCaseType(lang, item.type)}</strong><span>{item.id} · {translatedStatus(lang, item.status)}</span></div><b className={`priority-${item.priority}`}>{item.priority}</b><p>{item.summary}</p></Link>) : <p className="empty-state">{t.noCases}</p>}</div></>;
}

function NgoCaseDetail({ lang }: { lang: Language }) {
  const t = ngoText[lang]; const caseId = location.pathname.split("/").pop() || ""; const [detail, setDetail] = React.useState<CaseDetail | null>(null); const [loading, setLoading] = React.useState(true); const [note, setNote] = React.useState(""); const [busy, setBusy] = React.useState(false); const [error, setError] = React.useState(false); const [acknowledged, setAcknowledged] = React.useState(false);
  const load = React.useCallback(async () => { setLoading(true); try { setDetail(await ngoApi.detail(caseId)); setError(false); } catch { setError(true); } finally { setLoading(false); } }, [caseId]);
  React.useEffect(() => { void load(); }, [load]);
  if (loading) return <Loading lang={lang} />; if (error || !detail) return <div className="error-box"><p>{t.error}</p><button className="button button-small" onClick={() => void load()}>{t.retry}</button></div>;
  const update = async (body: Record<string, unknown>) => { setBusy(true); try { await ngoApi.updateCase(caseId, body); await load(); } finally { setBusy(false); } };
  const addNote = async (event: React.FormEvent) => { event.preventDefault(); if (!note.trim()) return; setBusy(true); try { await ngoApi.addNote(caseId, { author: "ngo-caseworker", text: note }); setNote(""); await load(); } finally { setBusy(false); } };
  const uploadEvidence = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; if (!file) return;
    if (!["image/jpeg", "image/png", "application/pdf"].includes(file.type) || file.size > 10 * 1024 * 1024) return;
    setBusy(true);
    try {
      const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer());
      const checksum = Array.from(new Uint8Array(digest)).map((value) => value.toString(16).padStart(2, "0")).join("");
      const created = await evidenceApi.createUpload(caseId, { fileName: file.name, mimeType: file.type, sizeBytes: file.size, consentPurpose: "case_support", consentAudience: "assigned_caseworkers" });
      const upload = await fetch(created.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type }, body: file });
      if (!upload.ok) throw new Error("upload failed");
      await evidenceApi.complete(caseId, created.evidence.id, checksum);
      await load();
    } finally { setBusy(false); event.target.value = ""; }
  };
  const downloadEvidence = async (id: string) => { const result = await evidenceApi.downloadUrl(id); window.open(result.url, "_blank", "noopener,noreferrer"); };
  return <><Link className="text-link" to="/ngo">← {t.back}</Link><div className="ngo-detail-head"><div><p className="eyebrow teal">{detail.case.id}</p><h1>{translatedCaseType(lang, detail.case.type)}</h1><p>{detail.case.summary}</p></div><button className="button button-small" onClick={() => void update({ status: "resolved" })} disabled={busy}>{t.save}</button></div><div className="detail-grid"><section className="list-panel"><h2>{t.status}</h2><div className="status-buttons">{["new", "assigned", "in_progress", "resolved"].map((status) => <button className={detail.case.status === status ? "filter active" : "filter"} onClick={() => void update({ status })} key={status}>{translatedStatus(lang, status)}</button>)}</div><label>{t.assigned}<input defaultValue={detail.case.owner || ""} onBlur={(e) => e.target.value && void update({ owner: e.target.value })} placeholder={lang === "hi" ? "केसवर्कर का नाम" : "Caseworker name"} /></label>{detail.case.priority === "high" && <div className="alert-card"><strong>{lang === "hi" ? "उच्च प्राथमिकता सुरक्षा अलर्ट" : "High priority safety alert"}</strong><button className="button button-small" onClick={() => setAcknowledged(true)} disabled={acknowledged}>{acknowledged ? t.acknowledged : t.acknowledge}</button></div>}</section><section className="list-panel"><h2>{t.notes}</h2>{detail.notes.map((item) => <div className="timeline-item" key={item.id}><strong>{item.author}</strong><span>{new Date(item.createdAt).toLocaleString()}</span><p>{item.text}</p></div>)}<form onSubmit={addNote} className="note-form"><textarea required value={note} onChange={(e) => setNote(e.target.value)} placeholder={t.note} /><button className="button button-small" disabled={busy}>{t.add}</button></form></section><section className="list-panel"><h2>{t.evidence}</h2><label className="button button-small">{t.upload}<input type="file" accept=".jpg,.jpeg,.png,.pdf" hidden onChange={(event) => void uploadEvidence(event)} /></label>{detail.evidence.length ? detail.evidence.map((item) => <div className="list-row" key={item.id}><strong>{item.fileName}</strong><span>{item.type} · {new Date(item.createdAt).toLocaleDateString()}</span>{item.available ? <button className="button button-small" onClick={() => void downloadEvidence(item.id)}>{t.download}</button> : <small>{t.scanning}</small>}</div>) : <p>{t.noCases}</p>}</section><section className="list-panel"><h2>{t.history}</h2>{detail.auditLog.map((item) => <div className="timeline-item" key={item.id}><strong>{item.action}</strong><span>{item.actor} · {new Date(item.timestamp).toLocaleString()}</span></div>)}</section></div></>;
}

function NgoAudit({ lang }: { lang: Language }) { const t = ngoText[lang]; const [entries, setEntries] = React.useState<CaseDetail["auditLog"]>([]); const [loading, setLoading] = React.useState(true); React.useEffect(() => { ngoApi.audit().then((result) => setEntries(result.entries)).finally(() => setLoading(false)); }, []); if (loading) return <Loading lang={lang} />; return <><h1>{t.audit}</h1><div className="list-panel">{entries.length ? entries.map((entry) => <div className="timeline-item" key={entry.id}><strong>{entry.action}</strong><span>{entry.actor} · {new Date(entry.timestamp).toLocaleString()}</span></div>) : <p>{t.noCases}</p>}</div></>; }

function NgoArea({ lang, logout }: { lang: Language; logout: () => void }) { return <main className="worker-app"><NgoNav lang={lang} logout={logout} /><section className="worker-content"><Routes><Route index element={<NgoInbox lang={lang} />} /><Route path="cases/:id" element={<NgoCaseDetail lang={lang} />} /><Route path="audit" element={<NgoAudit lang={lang} />} /></Routes></section></main>; }

function EmployerLogin({ setSession }: { setSession: (value: NgoSession) => void }) { const [email, setEmail] = React.useState(""); const [password, setPassword] = React.useState(""); const [error, setError] = React.useState(""); const submit = async (event: React.FormEvent) => { event.preventDefault(); try { const result = await authApi.employerLogin(email, password); const value = { email, token: result.accessToken, refreshToken: result.refreshToken, expiresAt: Date.now() + result.expiresIn * 1000 }; localStorage.setItem("pehchaan-employer-session", JSON.stringify(value)); setSession(value); } catch { setError("Employer credentials are invalid or access is pending approval."); } }; return <main className="auth-page"><form className="auth-card" onSubmit={submit}><p className="eyebrow teal">Employer portal</p><h1>Fair work transparency</h1><label>Email<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Password<input type="password" required value={password} onChange={(e) => setPassword(e.target.value)} /></label><button className="button">Sign in</button>{error && <p className="error">{error}</p>}</form></main>; }
function EmployerInterest() { const [sent, setSent] = React.useState(false); const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await employerApi.interest({ name: form.get("name"), email: form.get("email"), organization: form.get("organization"), message: form.get("message") }); setSent(true); }; return <main className="auth-page"><form className="auth-card" onSubmit={submit}><p className="eyebrow teal">Employer partnership</p><h1>Build trust with fair work records</h1>{sent ? <p className="success">Thank you. Our team will contact you after review.</p> : <><label>Name<input name="name" required /></label><label>Work email<input name="email" type="email" required /></label><label>Organization<input name="organization" required /></label><label>Message<textarea name="message" /></label><button className="button">Request onboarding</button></>}</form></main>; }
function EmployerArea({ logout }: { logout: () => void }) { const [data, setData] = React.useState<{ records: import("./api").EmployerRecord[]; compliance: { flagged: number; responded: number; responseRate: number } } | null>(null); const [error, setError] = React.useState(""); const [response, setResponse] = React.useState<Record<string, string>>({}); React.useEffect(() => { employerApi.dashboard().then(setData).catch(() => setError("Could not load employer records.")); }, []); if (error) return <main className="worker-content"><p className="error">{error}</p></main>; if (!data) return <Loading lang="en" />; return <main className="worker-app"><aside className="worker-nav"><Link className="brand" to="/">Pehchaan<span>.</span></Link><strong>Employer portal</strong><button className="logout-link" onClick={logout}>Log out</button></aside><section className="worker-content employer-portal"><p className="eyebrow teal">Responsible employer tools</p><h1>Fair work transparency</h1><div className="stats-grid"><div className="stat-card"><span>Flagged discrepancies</span><strong>{data.compliance.flagged}</strong></div><div className="stat-card"><span>Response rate</span><strong>{data.compliance.responseRate}%</strong></div><div className="stat-card"><span>Worker privacy</span><strong>Protected</strong></div></div><div className="list-panel"><h2>Wage records</h2>{data.records.length ? data.records.map((record) => <div className="list-row" key={record.id}><strong>{record.period}</strong><span>Promised ₹{record.promisedAmount} · Paid ₹{record.paidAmount} · {record.status}</span>{record.status === "disputed" && <><input value={response[record.id] || ""} onChange={(e) => setResponse({ ...response, [record.id]: e.target.value })} placeholder="Your response" /><button className="button button-small" onClick={() => void employerApi.respond(record.id, response[record.id] || "").then(() => setData({ ...data, records: data.records.map((item) => item.id === record.id ? { ...item, status: "responded" } : item) }))}>Respond</button></>}</div>) : <p>No consented wage records yet.</p>}</div><p className="helper">Private complaints, evidence, NGO notes, and other employers' data are never shown here.</p></section></main>; }

function App() {
  const [lang, setLang] = React.useState<Language>(() => localStorage.getItem("pehchaan-language") === "en" ? "en" : "hi");
  const [session, setSessionState] = React.useState<Session | null>(() => getSession());
  const [ngoSession, setNgoSession] = React.useState<NgoSession | null>(() => getNgoSession());
  const [employerSession, setEmployerSession] = React.useState<NgoSession | null>(() => { try { const value = JSON.parse(localStorage.getItem("pehchaan-employer-session") || "null"); return value?.expiresAt > Date.now() ? value : null; } catch { return null; } });
  const setSession = (value: Session) => { localStorage.setItem(sessionKey, JSON.stringify(value)); setSessionState(value); };
  const logout = () => { if (window.confirm(labels[lang].confirmLogout)) { void authApi.logout(session?.refreshToken); localStorage.removeItem(sessionKey); setSessionState(null); window.location.assign("/"); } };
  const updateLang = (value: Language) => { setLang(value); localStorage.setItem("pehchaan-language", value); };
  const ngoLogout = () => { if (window.confirm(ngoText[lang].logoutConfirm)) { void authApi.logout(ngoSession?.refreshToken); localStorage.removeItem(ngoSessionKey); setNgoSession(null); window.location.assign("/"); } };
  const employerLogout = () => { void authApi.logout(employerSession?.refreshToken); localStorage.removeItem("pehchaan-employer-session"); setEmployerSession(null); window.location.assign("/"); };
  return <><Navbar lang={lang} setLang={updateLang} /><Routes><Route path="/" element={<PublicHome lang={lang} />} /><Route path="/worker/login" element={session ? <Navigate to="/worker" replace /> : <Auth lang={lang} setSession={setSession} />} /><Route path="/worker/*" element={session ? <WorkerArea lang={lang} session={session} logout={logout} /> : <Navigate to="/worker/login" replace />} /><Route path="/ngo/login" element={ngoSession ? <Navigate to="/ngo" replace /> : <NgoLogin lang={lang} setSession={setNgoSession} />} /><Route path="/ngo/*" element={ngoSession ? <NgoArea lang={lang} logout={ngoLogout} /> : <Navigate to="/ngo/login" replace />} /><Route path="/employer/login" element={employerSession ? <Navigate to="/employer" replace /> : <EmployerLogin setSession={setEmployerSession} />} /><Route path="/employer/interest" element={<EmployerInterest />} /><Route path="/employer/*" element={employerSession ? <EmployerArea logout={employerLogout} /> : <Navigate to="/employer/login" replace />} /><Route path="*" element={<PublicPage lang={lang} title={lang === "hi" ? "पहचान" : "Pehchaan"} />} /></Routes><footer><div><Link className="brand" to="/">Pehchaan<span>.</span></Link><p>{lang === "hi" ? "हर श्रमिक सुरक्षित कल का हकदार है।" : "Every worker deserves a safer tomorrow."}</p></div></footer></>;
}

export default App;
